epochs: 300
batch_size: 32
learning-rate: 0.00005

# data options
input_dim: 2                  # number of image channels [1 - 3]: b0, t1, t2
output_dim: 1
data_root: /storage/connectome/GANBERT/data/sample/sample_b0_input_ver       # dataroot of training files
img_dir: /scratch/connectome/conmaster/Pycharm_projects/3D_brain2brain_GAN/Benchmark_2D/Generated_images/mean_b0_input_wgangp
